### ISSUE TITLE
Main query is throwing error

### ISSUE THREAD

**Issue by geramirez** [inkblotty/my-work-action#42]
I noticed this on my automation and others:
```
GraphqlResponseError: Request failed due to following response errors:
 - Search is currently unavailable
```

I looked into the query, but I'm not sure what's causing the problem.

**Comment by LisaKr** [comment]
- Slack discussion: https://github.slack.com/archives/C03ELSD7LUA/p1717575140580299
- Connected to this problem: https://github.com/github/issues-experience/actions/runs/9378468801/job/25828134884
- Other intel gathered today:
  - Offending change: https://github.com/github/github/commit/0d5dbd346d4b48386297e59a8db1030e0fbdf934
  - @alondahari's idea: only throwing if there are errors and there's no data in the response. We could potentially do something like `if results.error? && results.results.empty?` instead of just `if results.error?`
  -  Seems to be hard to replicate my-work workflow locally the action depends on @actions/core to get some environment variables. Alternatively, we can pull the `inkblotty/my-work-action` repo, change the usages of `core.getInput` with real data and test it with `npm run build && node dist/index.js`. 
  - [my-work-action/src/index.ts at f15d690d87560fda5949faa08e0a488e315a067d · inkblotty/my-work-action](https://github.com/inkblotty/my-work-action/blob/f15d690d87560fda5949faa08e0a488e315a067d/src/index.ts) is the reason why the message is not that complete, core.setFailed is using err.message and not the actual error, so stacktrace is lost

**Comment by gcapizzi** [comment]
This is due to a typo in the GraphQL query 😅 Our change interacted with it because [`Search::Query` treats `RequestError`s as server errors](https://github.com/github/github/blob/ea9396f6a9c65de80eeb7d6769eab4d42ddaf5b4/packages/search/app/models/search/query.rb#L606). I will start a conversation with the ES team about how to best tackle this, in the meantime #44 should take care of the issue here.

**Comment by geramirez** [comment]
@gcapizzi nice catch
